stages:
  - build
  - build-test
  - build-image
  - test
  - conda-build
  - push

variables:
  PROJ: "sccoos-sass-calibration"
  IMAGE: $PROJ:$CI_COMMIT_REF_NAME
  LINT_IMAGE: $PROJ-linter:$CI_COMMIT_REF_NAME
  AXIOM_LATEST: registry.axiom/$PROJ:latest
  AXIOM_TAG: registry.axiom/$PROJ:$CI_COMMIT_TAG
  DOCKER_BUILDKIT: 1


build_linter:
  stage: build
  script:
    - docker build $BUIDLOPTS -t $LINT_IMAGE docker/linter

build_image:
  stage: build-image
  script:
    - docker build $BUIDLOPTS -t $IMAGE .

lint:
  image: $LINT_IMAGE
  stage: test
  script:
    - flake8 sass

test:
  image: $IMAGE
  stage: test
  script:
    - pytest -sv tests --integration

push:
  stage: push
  only:
    - master
  script:
    - docker tag $IMAGE $AXIOM_LATEST
    - docker push $AXIOM_LATEST

push_tag:
  stage: push
  only:
    - tags
  script:
    - docker tag $IMAGE $AXIOM_TAG
    - docker push $AXIOM_TAG